apiVersion: v2
name: store
description: Store Provisioning Chart (WordPress wrapper)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: wordpress
    version: 28.1.7
    repository: https://charts.bitnami.com/bitnami
